### ISSUE TITLE
[nmo_oil_rig_v8] You can skip waiting for the extraction boat

### ISSUE THREAD

**Issue by dysphie** [dysphie/nmrih-community-maps#5]
You can skip waiting for the extraction boat by simply jumping off the main platform and landing on the extraction zone. trigger_teleport appears not to work.

1. Trigger boat objective
2. Head towards the railings and prepare to jump
3. `showtriggers 1; showtriggers_toggle` and land into the pencil-thin extraction brush

**Comment by ulreth** [comment]
Just tested this offline, teleport worked while i was on the air so i don't know what can cause this fail of trigger, are you sure its not working?
